{"name": "Проверить, что вернется сообщение об ошибке при неверном логине", "status": "passed", "start": 1723488299577, "stop": 1723488299946, "uuid": "98240cd6-2d1e-4e1d-9b6e-9a0ef8ffc6f0", "historyId": "14a96f3f8844eda06874e3757cc3460a", "testCaseId": "14a96f3f8844eda06874e3757cc3460a", "fullName": "tests.test_cuorier_login#test_login_courier_incorrect_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cuorier_login"}, {"name": "host", "value": "DESKTOP-C0DAUU0"}, {"name": "thread", "value": "15936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cuorier_login"}]}