{"name": "Проверить, что вернется сообщение об ошибке при неверном логине", "status": "passed", "start": 1723750641057, "stop": 1723750641432, "uuid": "4fe1eed0-fcfd-4e59-860a-9d9994e7f0b6", "historyId": "c9b8b2435786540c0ce500ba43998816", "testCaseId": "c9b8b2435786540c0ce500ba43998816", "fullName": "tests.test_cuorier_login.TestCourierLogin#test_login_courier_incorrect_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cuorier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-C0DAUU0"}, {"name": "thread", "value": "13260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cuorier_login"}]}